name: data_state_mobx
description: A powerful state machine for MobX management, which can be used in almost any application state.
version: 0.1.0
homepage: https://github.com/danielmagri/data_state

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  mobx: ^2.0.6+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.8
  flutter_lints: ^1.0.4
  flutter_mobx: ^2.0.4
  mobx_codegen: ^2.0.5+2

flutter:
